### ISSUE TITLE
Game keeps crashing when trying to load DulkirFabric

### ISSUE THREAD

**Issue by Ashgash01** [inglettronald/DulkirMod-Fabric#17]
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'architectury' at 'dev.architectury.utils.fabric.GameInstanceImpl::init'!

Thats the error it gives me...

**Comment by inglettronald** [comment]
Hey! Can you answer a couple of questions for me?
- What version of minecraft are you using?
- What version of Dulkirmod-fabric are you using?

**Comment by inglettronald** [comment]
nuh uh
