### ISSUE TITLE
Inventory Scale has several issues

### ISSUE THREAD

**Issue by MicrocontrollersDev** [inglettronald/DulkirMod-Fabric#18]
- Player doesn't render properly in inventory (using 1.05 scale for screenshot)
![image](https://github.com/user-attachments/assets/143f3f6b-b11b-427e-86e8-120046c2e361)
- Unable to drag items in inventory slots
- Creative scrollbar grab is in wrong position (y-axis only, x is fine)

**Comment by inglettronald** [comment]
😭 Ty for the report! I will look into it when I get back home from vacation in roughly 3-4 days.

If you're interested in poking around, the rendering issue looks like we need to modify the render context's scissor. Doesn't look like a Z fighting issue. I'm not immediately sure about the other two issues without looking at the actual code, which I don't feel like doing on my laptop.

**Comment by inglettronald** [comment]
Fixed now on latest commit!
