### ISSUE TITLE
Incorrect injection causing unexpected matrix stack manipulation.

### ISSUE THREAD

**Issue by kevinthegreat1** [inglettronald/DulkirMod-Fabric#7]
Hi, Skyblocker dev here. We recently received reports of screen/container features conflicting with DulkirMod-Fabric (see [Skyblocker#239](https://github.com/SkyblockerMod/Skyblocker/issues/239)). It seems that the matrix stack is being manipulated by Dulkir, caused by this injection, which injects before the `push` call and modifies the screen matrix when it should inject after the `push` call and only modify the tooltip matrix.

https://github.com/inglettronald/DulkirMod-Fabric/blob/0516a4be0c93d6a82dc23ba074a5ee6c6b8c181f/src/main/java/com/dulkirfabric/mixin/render/DrawContextMixin.java#L45-L51

**Comment by inglettronald** [comment]
Thanks for bringing this to my attention. I'll look into fixing this soon, but I am quite busy atm so it might be a bit.

**Comment by inglettronald** [comment]
Sorry for the complaints and stuff, I understand how frustrating it can be to have compatibility/dependency issues to deal with in support tickets.

**Comment by kevinthegreat1** [comment]
No problem, thanks for your work!
